spring.application.name=backend

server.port=8081

# Spring Security (basic login)
spring.security.user.name=admin
spring.security.user.password=admin

# Supabase PostgreSQL Database
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.mqyraqvcomlmvwfqqvbw
spring.datasource.password=QdVNG3BBDn590vy6
spring.datasource.driver-class-name=org.postgresql.Driver
supabase.url=https://mqyraqvcomlmvwfqqvbw.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xeXJhcXZjb21sbXZ3ZnFxdmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2ODMwOTgsImV4cCI6MjA5MDI1OTA5OH0.yL9ZLNVEE1qj-WuXALSNkijTh0SShjP8zz5tZ-l9h40

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: better logs
spring.jpa.properties.hibernate.format_sql=true

# File upload settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB