spring.application.name=backend

# Spring Security (basic login)
spring.security.user.name=admin
spring.security.user.password=admin

# Supabase PostgreSQL Database
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.mqyraqvcomlmvwfqqvbw
spring.datasource.password=QdVNG3BBDn590vy6
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: better logs
spring.jpa.properties.hibernate.format_sql=true